version: '3.8'

services:
  web:
    build: ./backend
    container_name: authguard_api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - auth_net
    restart: always

  db:
    image: postgres:15-alpine
    container_name: authguard_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=secure_db_password
      - POSTGRES_DB=authguard
    networks:
      - auth_net

volumes:
  postgres_data:

networks:
  auth_net:
    driver: bridge
